In [2]:
import pandas as pd
import numpy as np

In [40]:
tab_23 = pd.read_excel('tab_23.xls', skiprows = 4)
tab_23 = tab_23.set_index('Unnamed: 0')

In [32]:
median_zp = pd.DataFrame(index = np.arange(0,96))
median_zp['object_name']= tab_23.index
median_zp['median_pay']= tab_23.index
for i, idx in enumerate(tab_23.index):
    cumulate_pay = 0
    for j, clm in enumerate(tab_23.columns):
        cumulate_pay += float(tab_23.iloc[i,j+1])
        if cumulate_pay >= 50:
          numbers = clm.replace("от", "").replace("до", "").split()
          first_number = float(numbers[0].replace(",", "."))
          try:
            second_number = float(numbers[1].replace(",", "."))

            # Вычисление среднего значения
            average_value = (first_number + second_number) / 2
          except:
            average_value = first_number
          median_zp.loc[i,'median_pay'] = average_value
          break
# median_zp.to_csv('median_pay_23.csv')
median_zp

                      object_name median_pay
0            Российская Федерация   51850.05
1   Центральный Федеральный округ   65000.05
2            Белгородская область   41400.05
3                Брянская область   26800.05
4            Владимирская область   47900.05
..                            ...        ...
91               Амурская область   51850.05
92            Магаданская область   87500.05
93            Сахалинская область   87500.05
94   Еврейская автономная область   33295.05
95            Чукотский авт.округ   65000.05

[96 rows x 2 columns]

In [3]:
median_zp = pd.read_csv('median_pay_23.csv')

In [12]:
base_data = pd.read_csv('data_graduates_university_specialty_124_v20240709 (1).csv', sep = ';')
print(base_data)
df = base_data.merge(median_zp, on = 'object_name', how ='outer')
# print(df.columns)
df['regnorm_pay'] = df['average_salary']/df['median_pay_23']
df
# df.to_csv('df_status_regnorm.csv')

       object_level            object_name   gender  \
0            Регион      Кировская область  Мужской
1            Регион      Кировская область  Мужской
2            Регион      Кировская область  Мужской
3            Регион      Кировская область  Мужской
4            Регион      Кировская область  Мужской
...             ...                    ...      ...
599966       Регион  Волгоградская область  Женский
599967       Регион  Волгоградская область  Женский
599968       Регион  Волгоградская область  Женский
599969       Регион  Волгоградская область  Женский
599970       Регион  Волгоградская область  Женский

                                  education_level  year  \
0       СПО: квалифицированные рабочие и служащие  2019
1       СПО: квалифицированные рабочие и служащие  2019
2       СПО: квалифицированные рабочие и служащие  2019
3       СПО: квалифицированные рабочие и служащие  2019
4       СПО: квалифицированные рабочие и служащие  2019
...                                           ...   ...
599966                               Магистратура  2023
599967                               Магистратура  2023
599968                               Магистратура  2023
599969                               Магистратура  2023
599970                               Магистратура  2023

                                               university  \
0       Волго-Вятский колледж информатики, финансов, п...
1       Волго-Вятский колледж информатики, финансов, п...
2       Волго-Вятский колледж информатики, финансов, п...
3               Вятский автомобильно-промышленный колледж
4               Вятский автомобильно-промышленный колледж
...                                                   ...
599966  Российский университет кооперации (Волгоградск...
599967  Российский университет кооперации (Волгоградск...
599968  Российский экономический университет им. Г.В. ...
599969  Российский экономический университет им. Г.В. ...
599970  Российский экономический университет им. Г.В. ...

                           specialty_section  \
0                     Экономика и управление
1       Информатика и вычислительная техника
2                              Юриспруденция
3                     Экономика и управление
4                 Электро- и теплоэнергетика
...                                      ...
599966                Экономика и управление
599967                Экономика и управление
599968                Экономика и управление
599969                Экономика и управление
599970                Экономика и управление

                                                specialty specialty_code  \
0                                 Коммерция (по отраслям)       38.02.04
1                    Информационные системы (по отраслям)       09.02.04
2                         Правоохранительная деятельность       40.02.02
3       Товароведение и экспертиза качества потребител...       38.02.05
4       Техническая эксплуатация и обслуживание электр...       13.02.11
...                                                   ...            ...
599966                                         Менеджмент       38.04.02
599967                                          Экономика       38.04.01
599968                                         Менеджмент       38.04.02
599969                                   Финансы и кредит       38.04.08
599970                                          Экономика       38.04.01

        count_graduate  percent_employed  average_salary     oktmo     okato
0                   10         70.000000             NaN  33000000  33000000
1                    8         62.500000             NaN  33000000  33000000
2                    4         50.000000             NaN  33000000  33000000
3                    2          0.000000             NaN  33000000  33000000
4                   22         95.454545     73733.91842  33000000  33000000
...                ...               ...             ...       ...       ...
599966               6        100.000000             NaN  18000000  18000000
599967              10         80.000000             NaN  18000000  18000000
599968               3         66.666667             NaN  18000000  18000000
599969               6        100.000000             NaN  18000000  18000000
599970               7        100.000000             NaN  18000000  18000000

[599971 rows x 14 columns]

,object_level,object_name,gender,education_level,year,university,specialty_section,specialty,specialty_code,count_graduate,percent_employed,average_salary,oktmo,okato,median_pay_23,regnorm_pay
0,Регион,Алтайский край,Мужской,СПО: квалифицированные рабочие и служащие,2019,Алтайская академия гостеприимства,Экономика и управление,Коммерция (по отраслям),38.02.04,10,80.000000,NaN,1000000,1000000,39790.05,NaN
1,Регион,Алтайский край,Мужской,СПО: квалифицированные рабочие и служащие,2019,Алтайская академия гостеприимства,Изобразительное и прикладные виды искусств,Техника и искусство фотографии,54.02.08,3,33.333333,NaN,1000000,1000000,39790.05,NaN
2,Регион,Алтайский край,Мужской,СПО: квалифицированные рабочие и служащие,2019,Алтайская академия гостеприимства,Сервис и туризм,Организация обслуживания в общественном питании,43.02.01,6,83.333333,NaN,1000000,1000000,39790.05,NaN
3,Регион,Алтайский край,Мужской,СПО: квалифицированные рабочие и служащие,2019,Алтайская академия гостеприимства,Сервис и туризм,Гостиничный сервис,43.02.11,8,75.000000,NaN,1000000,1000000,39790.05,NaN
4,Регион,Алтайский край,Мужской,СПО: квалифицированные рабочие и служащие,2019,Алтайская академия гостеприимства,Промышленная экология и биотехнологии,Технология продукции общественного питания,19.02.10,26,69.230769,33335.64000,1000000,1000000,39790.05,0.837788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599966,Регион,Ярославская область,Женский,Магистратура,2023,Ярославский государственный университет им. П....,Науки о Земле,Экология и природопользование,05.04.06,4,100.000000,NaN,78000000,78000000,47900.05,NaN
599967,Регион,Ярославская область,Женский,Магистратура,2023,Ярославский государственный университет им. П....,Юриспруденция,Юриспруденция,40.04.01,41,90.243902,60698.43528,78000000,78000000,47900.05,1.267189
599968,Регион,Ярославская область,Женский,Магистратура,2023,Ярославский государственный университет им. П....,Психологические науки,Психология,37.04.01,10,80.000000,NaN,78000000,78000000,47900.05,NaN
599969,Регион,Ярославская область,Женский,Магистратура,2023,Ярославский государственный университет им. П....,Химия,Химия,04.04.01,2,100.000000,NaN,78000000,78000000,47900.05,NaN
599970,Регион,Ярославская область,Женский,Магистратура,2023,Ярославский государственный университет им. П....,Языкознание и литературоведение,Филология,45.04.01,9,88.888889,NaN,78000000,78000000,47900.05,NaN

In [22]:
df = pd.read_csv('df_with_status_specialty_regnorm.csv')
profil = pd.read_csv('profil.csv')

df = df.merge(profil, on = 'university', how ='outer').drop(['Unnamed: 0_y', 'Unnamed: 0_x'], axis = 1)
df['niu'] = df['niu'].notnull().astype(int)
df['fed'] = df['fed'].notnull().astype(int)
df['opo'] = df['opo'].notnull().astype(int)
df['pri'] = df['pri'].notnull().astype(int)
df

/tmp/ipykernel_71135/1625858802.py:1: DtypeWarning: Columns (18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('df_with_status_specialty_regnorm.csv')

,object_level,object_name,gender,education_level,year,university,specialty_section,specialty,specialty_code,count_graduate,...,niu,fed,opo,pri,median_pay_23,regnorm_pay,specialty_top_level,top_specialty,is_specialised,profil
0,Регион,Республика Адыгея,Мужской,"Бакалавриат, специалитет",2019.0,Адыгейский государственный университет,Юриспруденция,Юриспруденция,40.03.01,58.0,...,0,0,0,1,33295.05,1.679143,40.0,40.0,0.0,1.0
1,Регион,Республика Адыгея,Мужской,"Бакалавриат, специалитет",2019.0,Адыгейский государственный университет,Юриспруденция,Юриспруденция,40.03.01,58.0,...,0,0,0,1,33295.05,1.679143,40.0,40.0,0.0,1.0
2,Регион,Республика Адыгея,Мужской,"Бакалавриат, специалитет",2019.0,Адыгейский государственный университет,Юриспруденция,Юриспруденция,40.03.01,58.0,...,0,0,0,1,33295.05,1.679143,40.0,40.0,0.0,1.0
3,Регион,Республика Адыгея,Мужской,"Бакалавриат, специалитет",2019.0,Адыгейский государственный университет,Юриспруденция,Юриспруденция,40.03.01,58.0,...,0,0,0,1,33295.05,1.679143,40.0,40.0,0.0,1.0
4,Регион,Республика Адыгея,Мужской,"Бакалавриат, специалитет",2019.0,Адыгейский государственный университет,Юриспруденция,Юриспруденция,40.03.01,58.0,...,0,0,0,1,33295.05,1.679143,40.0,40.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881960,Регион,Ярославская область,Женский,"Бакалавриат, специалитет",2023.0,Ярославский государственный университет им. П....,Математика и механика,Прикладная математика и информатика,01.03.02,23.0,...,0,0,0,0,47900.05,0.984051,1.0,38.0,0.0,0.0
881961,Регион,Ярославская область,Женский,"Бакалавриат, специалитет",2023.0,Ярославский государственный университет им. П....,Математика и механика,Прикладная математика и информатика,01.03.02,23.0,...,0,0,0,0,47900.05,0.984051,1.0,38.0,0.0,0.0
881962,Регион,Ярославская область,Женский,"Бакалавриат, специалитет",2023.0,Ярославский государственный университет им. П....,Математика и механика,Прикладная математика и информатика,01.03.02,23.0,...,0,0,0,0,47900.05,0.984051,1.0,38.0,0.0,0.0
881963,Регион,Ярославская область,Женский,"Бакалавриат, специалитет",2023.0,Ярославский государственный университет им. П....,Математика и механика,Прикладная математика и информатика,01.03.02,23.0,...,0,0,0,0,47900.05,0.984051,1.0,38.0,0.0,0.0
881964,Регион,Ярославская область,Женский,"Бакалавриат, специалитет",2023.0,Ярославский государственный университет им. П....,Математика и механика,Прикладная математика и информатика,01.03.02,23.0,...,0,0,0,0,47900.05,0.984051,1.0,38.0,0.0,0.0

In [62]:
df = pd.read_csv('regnorm_profil_status.csv').drop(['Unnamed: 0'], axis = 1)
df['world_ranking_1000'] = np.zeros(72028)
df['world_ranking'] = np.zeros(72028)

cursed_list = [
    'Московский государственный университет им. М.В. Ломоносова',
    'Московский физико-технический институт',
    'Санкт-Петербургский государственный университет',
    "Новосибирский национальный исследовательский государственный университет",
    "Национальный исследовательский Томский государственный университет",
    'Национальный исследовательский ядерный университет """"МИФИ""""',
    "Российский университет дружбы народов",
    'Национальный исследовательский университет """"Высшая школа экономики""""',
    "Санкт-Петербургский политехнический университет Петра Великого",
    "Московский государственный технический университет им. Н.Э. Баумана",
    "Санкт-Петербургский горный университет",
    "Санкт-Петербургский национальный исследовательский университет информационных технологий, механики и оптики",
    "Казанский (Приволжский) федеральный университет",
    'Национальный исследовательский технологический университет """"МИСиС""""',
    "Национальный исследовательский Томский политехнический университет",
    "Волгоградский государственный технический университет"
]

medium_list = [
    "Российский национальный исследовательский медицинский университет им. Н.И. Пирогова Министерства здравоохранения Российской Федерации",
    "Национальный исследовательский университет """"Московский институт электронной техники""""",
    ""
]
cursed_mask = df['university'].isin(cursed_list)
medium_cursed_mask = df['university'].isin(medium_list) | cursed_mask
df.loc[cursed_mask, 'world_ranking_1000'] = 1
df.loc[medium_cursed_mask, 'world_ranking'] = 1

df[df.world_ranking_1000 == 1]['university'].unique()

array(['Волгоградский государственный технический университет',
       'Казанский (Приволжский) федеральный университет',
       'Московский государственный технический университет им. Н.Э. Баумана',
       'Московский государственный университет им. М.В. Ломоносова',
       'Московский физико-технический институт',
       'Национальный исследовательский Томский государственный университет',
       'Национальный исследовательский Томский политехнический университет',
       'Новосибирский национальный исследовательский государственный университет',
       'Российский университет дружбы народов',
       'Санкт-Петербургский горный университет',
       'Санкт-Петербургский государственный университет',
       'Санкт-Петербургский национальный исследовательский университет информационных технологий, механики и оптики',
       'Санкт-Петербургский политехнический университет Петра Великого'],
      dtype=object)